defaults:
  - _self_
  - model: LSTM # random_forest #orbit - random_forest - sarimax - lstm - gru - prophet
  - dataset_loader: CoinMarket #Bitmex
  - metrics

validation_method: simple #simple - cross_validation
symbol: ETH
load_path: E:\MyWorks\CrptoPrediction_Demo\CryptoPredictions\data\bitcoin-helformer.csv
save_dir:
dataset_path:

